on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push (Rei)
jobs:
  web-deploy:
    name: 🎉 Deploy Rei's
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.mediarei.com
          server-dir: ./customers/3/d/7/mediarei.com/httpd.www/vlp-website/
          username: mediarei.com
          password: ${{ secrets.REI_FTP_PASSWORD }}
